### ISSUE TITLE
glcddriver.c

### ISSUE THREAD

**Issue by zombielinux** [lucianm/GLCDprocDriver#1]
I seem to be having an issue compiling glcddriver on Archlinux. I have graphlcd-base-0.1.9 installed. I get errors after running "make". Here is the paste http://paste.debian.net/12391/

**Comment by lucianm** [comment]
Have you also tried the older glcdprocdriver-0.0.6? As stated on the homepage and also the download page, 0.1.0 is for graphlcd-base _greater_ than 0.1.9, which still means something like that can only be obtained from their Git repository, more specific, the "touchcol" branch. Hope this helps, please tell me if it does and close the issue if so (if you're allowed to do so), thanks.

**Comment by ConiKost** [comment]
I suggest to close this issue, as no answer in 8 years ;-)

**Comment by zombielinux** [comment]
@ConiKost @lucianm 

Yep. We can close this. The hardware this was attached to is unfortunately long gone. File this one under "unreproducable"

**Comment by lucianm** [comment]
::-) well, I still have it here, but have to confess, didn't boot that PC up anymore for a long time.
